version: '3'

services:
  composer:
    container_name: laravel-composer
    image: composer:latest
    volumes:
      - .:/app
    command: install --ignore-platform-reqs

  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - composer